# 公共配置文件
spring:
  application:
    name: next-bi-backend
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.252.5:3306/next_bi_db
    username: next_bi_db
    password: kKWd5TP8M8sZbDMC
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 43.143.20.63
    port: 6389
    timeout: 5000
#    password: 0304@[smj]
    Auth: 0304@[smj]
  rabbitmq:
    port: 5672
    host: 43.143.20.63
    username: admin
    password: pzvXxE6g0o

  #    password: redis
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://43.143.20.63:9200
    username: elastic
    password: elastic123
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 100MB
      max-request-size: 150MB
server:
  address: 0.0.0.0
  port: 18123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

yuapi:
  client:
    access-key: x4efjrn1gzl70iubppr46ht026146glm
    secret-key: ox6902pv2jh8ex3fd7bch4kg7n8ug7w3

nexura:
  bi:
    integral: 5